### ISSUE TITLE
USER STORY: View products

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#1]
As a **Site User** I can **see all available products listed** so that I can **make purchase selections**

## Acceptance Criteria

- [x]  Page listing all products
- [x]  Page listing products of same category

## Tasks

- [x]  Create view and template for all products/categories
- [x]  Create view and template for sorting products by category
