### ISSUE TITLE
USER STORY: Sort products

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#10]
As a **Site User** I can **sort products by category** so that I can **view only products that are relevant to me**

## Acceptance Criteria

- [x] Category links in navigation
- [x] Category links in product detail
- [x] Links list only products with respective category

## Tasks

- [x] Include query function in links directing to specific category page
- [x] Create view that renders only products of same category and template
