### ISSUE TITLE
USER STORY: Search option

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#11]
As a **Site User** I can **search products by search term** so that I can **find specific products**

## Acceptance Criteria

- [ ] Search bar easily accessible throughout site
- [ ] Products can be filtered by user input

## Tasks

- [ ] Include query function in products view
