### ISSUE TITLE
USER STORY: Select quantity

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#13]
As a **Site User** I can **easily choose the quantity of each product** so that I can **be sure to get the amount I want**

## Acceptance Criteria

- [x] Quantity input field in product detail view
- [x] Larger Increment/Decrement buttons for easy input on mobile

## Tasks

- [x] Quantity input value to be stored in basket
- [x] Render buttons and write JS functionality
