### ISSUE TITLE
USER STORY: View basket

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#14]
As a **Site User** I can **quickly see what items are in my basket** so that I can **keep informed about my selection and the total cost**

## Acceptance Criteria

- [x] Basket page listing all selected items
- [x] Includes quantity, subtotal and total

## Tasks

- [x] Store basket data in session
- [x] Create basket view and template
