### ISSUE TITLE
USER STORY: Payment

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#16]
As a **Site User** I can **quickly fill out a payment form** so that I can **checkout easily**

## Acceptance Criteria

- [x] Clearly labeled payment form for billing and delivery information
- [x] Form pre-populated for registered users with profile

## Tasks

- [x] Set up Stripe payment system
- [x] Create checkout page with payment form
