### ISSUE TITLE
USER STORY: Order confirmation email

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#18]
As a **Site User** I **receive an email after successful checkout** so that I can **keep confirmations of my online purchases**

## Acceptance Criteria

- [x] Confirmation email to user after checkout
- [x] Email contains billing and delivery info as well as order contents

## Tasks

- [x] Write email content text document
- [x] Set up email sending functionality
