### ISSUE TITLE
USER STORY: Save user information

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#19]
As a **registered Site User** I can **save my personal information in my profile** so that I can **complete purchases more quickly**

## Acceptance Criteria

- [x] User profile funcitionality, only accessible to registered users
- [x] Allows users to store personal information such as delivery info via checkout

## Tasks

- [x] Include checkbox to store user info for registered users in checkout form
