### ISSUE TITLE
USER STORY: View product details

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#2]
As a **Site User** I can **click on any product** so that I can **find out about the price and description**

## Acceptance Criteria

- [x] Product details page listing all necessary information incl. price

## Tasks

- [x] Create view to render product details (Product model fields) in template
- [x] Create product details template
