### ISSUE TITLE
USER STORY: Social media links

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#23]
As a **Site User** I can **click on links to site related social media** so that I can **find out more about the business' activity**

## Acceptance Criteria

- [x] Footer with intituive social media icon links
- [x] Links open in new tab

## Tasks

- [x] Create footer icons in base template (fontawesome or iconify for icons)
- [x] Link to respective page
- [x] Include rel="noopener noreferrer" attributes in anchor tags
