### ISSUE TITLE
USER STORY: Browse forum

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#26]
As a **Site User** I can **access the forum and browse posts** so that I can **find advice or reviews on different products and related topics**

## Acceptance Criteria

- [x] Forum link in navigation
- [x] All posts accessible to any user
- [x] Posts ordered by date (newest first), include author name and type of post

## Tasks

- [x] Create view to render all forum posts in template
