### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#3]
As a **Site User** I can **see a responsive navbar at the top** so that I can **navigate the site easily**

## Acceptance Criteria

- [x] Responsive navbar
- [x] Descriptive links
- [x] Logo as default home button

## Tasks

- [x] Use bootstrap responsive nav element with hamburger drop-down
- [x] Name links clearly and intuitively
- [x] Link logo to homepage
