### ISSUE TITLE
USER STORY: Alert user actions

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#30]
As a **Site User** I can **see an alert message after each action taken** so that I know **my actions were successful**

## Acceptance Criteria

- [x] Alert message pop-up after each user action
- [x] Message is clear and discriptive with appropriate colour coding

## Tasks

- [x] Utilise bootstrap alerts
- [x] Include django messages in views where feedback is necessary
