### ISSUE TITLE
USER STORY: Delete forum post (admin)

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#31]
As an **Admin User** I can **delete existing forum entries** so that I can **avoid listing out of date content**

## Acceptance Criteria

- [x] Delete entry option only accessible to admin user
- [x] Request user confirmation before deleting product

## Tasks

- [x] Add delete link to entry details page
- [x] Protect delete button by asking user to confirm action
