### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#5]
As a **Site User** I can **register an account** so that I can **save personal information and contribute to the forum**

## Acceptance Criteria

- [x] Secure sign up lets user create account

## Tasks

- [x] Install Django Allauth
- [x] Customise sign up page
