### ISSUE TITLE
USER STORY: Login/Logout

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#6]
As a **Site User** I can **easily log into/out of my account** so that I can **access my personal profile and forum activity**

## Acceptance Criteria

- [x] Simple login/logout form
- [x] Only accessible for registered users

## Tasks

- [x] Use installed Django Allauth
- [x] Customise login/logout page
