### ISSUE TITLE
USER STORY: User profile

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kay-ddggxh/chirpy_chooks#9]
As a **registered Site User** I can **set up a profile** so that I can **save my personal information and view my order history**

## Acceptance Criteria

- [x] Personal profile page accessible to authenticated users
- [x] Profile information form to update user info  

## Tasks

- [x] Create template and form
- [x] Create view to save user input in profile form
